require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe V1::UsersController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # User. As you add validations to User, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    FactoryGirl.build(:valid_user).attributes
  }

  let(:invalid_attributes) {
    FactoryGirl.build(:invalid_user).attributes
  }

  let(:new_attributes) {
    FactoryGirl.build(:valid_user).attributes
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # UsersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  # strong parameters
  let(:valid_params) {  %w(id created_at updated_at).each do |key|
                          valid_attributes.delete(key)
                        end
                        valid_attributes
                      }
  let(:invalid_params) { { user: { sql_inject: 'SELECT user;' } } }

  describe 'API security' do
    context 'when new user is created' do
      it { expect(User).to receive(:create!).with(valid_params)
           post :create, params: {user: valid_params}, session: valid_session
         }
    end

    context 'when old user is updated' do
      it { user = User.create! new_attributes
           expect_any_instance_of(User).to receive(:update!).with(valid_params)
           put :update, params: {id: user.to_param, user: valid_params}, session: valid_session
         }
    end

    context 'when a hacker tries to make sql_injection' do
      it { expect(User).to receive(:create!).with({})
           post :create, params: invalid_params, session: valid_session
         }
    end
  end

  # CRUD
  describe "GET #index" do
    # route
    it { should route(:get, '/v1/users').to(action: :index) }

    it "returns a success response" do
      user = User.create! valid_attributes

      get :index, params: {}, session: valid_session
      expect(response).to be_success
    end
  end

  describe "GET #show" do
    # route
    it { should route(:get, '/v1/users/1').to(action: :show, id: 1) }

    # callback
    it { should use_before_action(:set_user) }

    it "returns a success response" do
      user = User.create! valid_attributes

      get :show, params: {id: user.to_param}, session: valid_session
      expect(response).to be_success
    end
  end

  describe "POST #create" do
    # route
    it { should route(:post, '/v1/users').to(action: :create) }

    context "with valid params" do
      it "creates a new User" do
        expect {
          post :create, params: {user: valid_attributes}, session: valid_session
        }.to change(User, :count).by(1)
      end

      it "renders a JSON response with the new user" do

        post :create, params: {user: valid_attributes}, session: valid_session
        expect(response).to have_http_status(:created)
        expect(response.content_type).to eq('application/json')
        user_last_sanitized = ['created_at',]
        expect(JSON.parse(response.body)).to eq(User.last.as_json(:except => [:created_at,:updated_at]))
        expect(response.location).to eq(v1_user_url(User.last))
      end
    end

    context "with invalid params" do
      it "renders a JSON response with errors for the new user" do

        post :create, params: {user: invalid_attributes}, session: valid_session
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq('application/json')
      end
    end
  end

  describe "PUT #update" do
    # routes
    it { should route(:put, '/v1/users/1').to(action: :update, id: 1) }
    it { should route(:patch, '/v1/users/1').to(action: :update, id: 1) }

    # callbacks
    it { should use_before_action(:set_user) }

    context "with valid params" do

      it "updates the requested user" do
        user = User.create! valid_attributes
        old_name = user.name

        put :update, params: {id: user.to_param, user: new_attributes}, session: valid_session
        user.reload
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to eq('application/json')
        expect(user.created_at).not_to eq(user.updated_at)
        expect(JSON.parse(response.body)['name']).not_to eq(old_name)
      end

      it "renders a JSON response with the user" do
        user = User.create! valid_attributes

        put :update, params: {id: user.to_param, user: valid_attributes}, session: valid_session
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to eq('application/json')
      end
    end

    context "with invalid params" do
      it "renders a JSON response with errors for the user" do
        user = User.create! valid_attributes

        put :update, params: {id: user.to_param, user: invalid_attributes}, session: valid_session
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq('application/json')
      end
    end
  end

  describe "DELETE #destroy" do
    # route
    it { should route(:delete, '/v1/users/1').to(action: :destroy, id: 1) }

    # callbacks
    it { should use_before_action(:set_user) }

    it "destroys the requested user" do
      user = User.create! valid_attributes
      expect {
        delete :destroy, params: {id: user.to_param}, session: valid_session
      }.to change(User, :count).by(-1)
    end
  end

  describe 'exception handler' do
    context "when user doesn't exist" do
      subject { get :show, params: {id: '1_000'}, session: valid_session }
      it { is_expected.to have_http_status(:not_found) }
    end

    context "when user is not valid" do
      subject { post :create, params: {user: invalid_attributes}, session: valid_session }
      it { is_expected.to have_http_status(:unprocessable_entity) }
    end

    context "when raises a bug" do
      let(:user) { User.create! valid_attributes }

      before {
        V1::UsersController.redefine_method('destroy') do
          raise Exception
        end
      }
      after {
        V1::UsersController.redefine_method('destroy') do
          @user.destroy
        end
      }

      subject { delete :destroy, params: {id: user.to_param}, session: valid_session }
      it { is_expected.to have_http_status(:internal_server_error) }
    end
  end

end
